spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/gper-mall/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: 192.168.216.128
    port: 6379
  # 链路追踪数据发送，1.0代表所有数据大发送过去
  sleuth:
    sampler:
      probability: 1.0
  # 链路追踪数据展示地址，需要在服务器上启动zikbin应用，自行下载  java jar  xxxx.jar
  zipkin:
    base-url: http://192.168.216.128:9411/
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
logging:
  level:
    root: debug