spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh


