spring:
  application:
    name: spring-cloud-config-server-9091
  # 配置配置文件的来源 git,分布式配置中心config，必须指定一个git的来源，不指定启动机会报错
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/gupao_mic/spring-cloud-config-server.git
#          username: 16607491862
#          password: "!q@w#e$r123"
          uri: https://gitee.com/mafenglei/spring-cloud-conifg-server.git
          username: mafenglei
          password: mfl900114@
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 192.168.216.128:9092
    consumer:
      group-id: config-server

# 端口
server:
  port: 9091

# 指向服务注册配置中心地址
eureka:
  client:
    service-url:
       defaultZone: http://localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh