spring:
  application:
    name: spring-cloud-config-server-9091
  # 配置配置文件的来源 git,分布式配置中心config，必须指定一个git的来源，不指定启动机会报错
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/gupao_mic/spring-cloud-config-server.git
#          username: 16607491862
#          password: "!q@w#e$r123"
          uri: https://gitee.com/mafenglei/spring-cloud-conifg-server.git
          username: mafenglei
          password: mfl900114@
    #  开启bus的配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  # 配置kafka地址 默认端口是9092,启动kafka之前必须启动zookeeper
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    # kafaka分组信息 不同组可以收到不同的消息
    consumer:
      group-id: config-server
  # 如果不想用远程配置，可以配置spring.profiles.active=native
#  profiles:
#    active: native

# 端口
server:
  port: 9091

# 指向服务注册配置中心地址
eureka:
  client:
    service-url:
       defaultZone: http://localhost:9090/eureka

# 配置消息总线bus的信息，开放刷新refresh的端点，就是后面刷线的话，就会触发这个端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


